# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftSample
  pod "RxSwift"
  pod "RxCocoa"
  pod "Alamofire"
  pod "RxRealmDataSources"
  pod "ObjectMapper"

  target 'RxSwiftSampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod "RxTest"
    pod "RxBlocking"
  end

  target 'RxSwiftSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
